# Generated by Django 4.2.16 on 2026-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_storage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
