# Generated by Django 4.2.16 on 2026-05-09 09:29

"""
Migration 0014: Add GIN index on search_vector for FTS performance.

NOTE: This index was originally created in migration 0006 via RunSQL with
``CREATE INDEX IF NOT EXISTS``. This migration uses the same safe approach
to avoid a ``DuplicateTable`` error when the index already exists.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_change_embedding_dim_to_1024'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS chunk_search_vector_gin "
                "ON document_chunks USING GIN (search_vector)"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS chunk_search_vector_gin"
            ),
        ),
    ]
