# Generated by Django 4.2.16 on 2026-05-09 09:29

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_change_embedding_dim_to_1024'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_gin'),
        ),
    ]
