# Generated by Django 4.2.16 on 2026-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_documentchunk_chunk_search_vector_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hub_type',
            field=models.CharField(blank=True, choices=[('legislation', 'Legislation'), ('judicial_precedent', 'Judicial Precedent'), ('advisory_opinion', 'Advisory Opinion')], db_index=True, help_text="Legal knowledge hub this document belongs to: 'legislation', 'judicial_precedent', or 'advisory_opinion'. Null/blank means not a reference document.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='hub_type',
            field=models.CharField(blank=True, db_index=True, help_text='Denormalized hub_type from the parent Document for efficient cross-document filtering without JOINs.', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['hub_type'], name='document_ch_hub_typ_798d7f_idx'),
        ),
    ]
