# Generated by Django 4.2.16 on 2026-05-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_hub_type_documentchunk_hub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tables_data',
            field=models.JSONField(blank=True, default=list, help_text="Extracted table data as a list of dicts with keys: 'page', 'bbox', 'markdown', 'semantic_text'. Populated during text extraction and consumed during chunking."),
        ),
    ]
