# Generated by Django 4.2.16 on 2026-05-16 09:50

"""
Migration 0017: Add GIN index on search_vector for FTS performance.

NOTE: This index was originally created in migration 0006 via RunSQL with
``CREATE INDEX IF NOT EXISTS``, and re-created in migration 0014 using the
same safe approach.

We use ``RunSQL`` with ``IF NOT EXISTS`` (matching 0006 and 0014) rather than
Django's ``AddIndex`` operation, because ``AddIndex`` translates to a plain
``CREATE INDEX`` which fails with:

    django.db.utils.ProgrammingError: relation "chunk_search_vector_gin"
    already exists

when the index already exists in the database (e.g. during test database setup
where all migrations run sequentially).
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_add_tables_data_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS chunk_search_vector_gin "
                "ON document_chunks USING GIN (search_vector)"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS chunk_search_vector_gin"
            ),
        ),
    ]
