# Generated by Django 4.2.16 on 2026-04-21 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('extract', 'Extract'), ('chunk', 'Chunk'), ('embed', 'Embed')], max_length=50)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='documents.document')),
            ],
            options={
                'db_table': 'processing_tasks',
                'indexes': [models.Index(fields=['document'], name='processing__documen_5bacb3_idx'), models.Index(fields=['celery_task_id'], name='processing__celery__7943f0_idx'), models.Index(fields=['status'], name='processing__status_2b4415_idx')],
            },
        ),
    ]
