# Generated by Django 4.2.16 on 2026-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_celery_task_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingtask',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
