"""
Django settings for DocuChat project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

# Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    DJANGO_SECRET_KEY=(str, 'django-insecure-development-key-change-in-production'),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    DATABASE_URL=(str, 'postgresql://docuchat:docuchat@localhost:5432/docuchat'),
    REDIS_URL=(str, 'redis://localhost:6379/0'),
    OPENAI_API_KEY=(str, ''),
    GOOGLE_API_KEY=(str, ''),
    GEMINI_EMBEDDING_MODEL=(str, 'gemini-embedding-001'),
    OLLAMA_BASE_URL=(str, 'http://localhost:11434'),
    EMBEDDING_PROVIDER=(str, 'google'),
    CHAT_PROVIDER=(str, 'openai'),
    CHAT_API_KEY=(str, ''),
    CHAT_BASE_URL=(str, 'https://api.openai.com/v1'),
    GEMINI_CHAT_MODEL=(str, 'gemini-2.0-flash'),
    OLLAMA_CHAT_MODEL=(str, 'llama3'),
    OPENAI_EMBEDDING_MODEL=(str, 'text-embedding-3-small'),
    OLLAMA_EMBEDDING_MODEL=(str, 'bge-m3'),
    EMBEDDING_DIMENSION=(int, 1024),
    VECTOR_SEARCH_PROBES=(int, 10),
    # OpenRouter Embedding Configuration
    OPENROUTER_API_KEY=(str, ''),
    OPENROUTER_BASE_URL=(str, 'https://openrouter.ai/api/v1'),
    OPENROUTER_EMBEDDING_MODEL=(str, 'bge-m3'),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',
    'django_filters',
    'pgvector.django',
    
    # Local apps
    'core',
    'users',
    'documents',
    'conversations',
    'tasks',
    'api_keys',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': env.db('DATABASE_URL', default='postgresql://docuchat:docuchat@localhost:5432/docuchat'),
}

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS Settings
# Read from DJANGO_CORS_ALLOWED_ORIGINS env var (set in docker-compose.yml),
# falling back to localhost origins for local development.
CORS_ALLOWED_ORIGINS = env.list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    default=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost",
        "http://127.0.0.1",
    ],
)

CORS_ALLOW_CREDENTIALS = True

# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=env('REDIS_URL', default='redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=env('REDIS_URL', default='redis://localhost:6379/1'))
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_TASK_ACKS_LATE = True          # Tasks re-queued if worker crashes
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_RETRY_BACKOFF = True       # Exponential backoff
CELERY_TASK_RETRY_BACKOFF_MAX = 600    # Max 10 minutes between retries
CELERY_TASK_RETRY_JITTER = True        # Add randomness to backoff

# ---------------------------------------------------------------------------
# Cache Configuration (Redis via django-redis)
# ---------------------------------------------------------------------------
# Reuses the same Redis URL as Celery (default: redis://localhost:6379/0).
# Database 1 is used for caching to avoid key collisions with Celery.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_CACHE_URL", default="redis://localhost:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "IGNORE_EXCEPTIONS": True,  # Cache failures never break the app
            "SOCKET_CONNECT_TIMEOUT": 2,  # seconds
            "SOCKET_TIMEOUT": 3,  # seconds
        },
        "KEY_PREFIX": "docuchat",
    }
}

# OpenAI Configuration
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')

# Google Gemini API Configuration
GOOGLE_API_KEY = env('GOOGLE_API_KEY', default='')
GEMINI_EMBEDDING_MODEL = env('GEMINI_EMBEDDING_MODEL', default='text-embedding-004')

# Embedding Provider Configuration
OLLAMA_BASE_URL = env('OLLAMA_BASE_URL', default='http://host.docker.internal:11434')
EMBEDDING_PROVIDER = env('EMBEDDING_PROVIDER', default='google')
CHAT_PROVIDER = env('CHAT_PROVIDER', default='openai')
OPENAI_EMBEDDING_MODEL = env('OPENAI_EMBEDDING_MODEL', default='text-embedding-3-small')
OLLAMA_EMBEDDING_MODEL = env('OLLAMA_EMBEDDING_MODEL', default='bge-m3')
EMBEDDING_DIMENSION = env('EMBEDDING_DIMENSION', default=1024)
GEMINI_CHAT_MODEL = env('GEMINI_CHAT_MODEL', default='gemini-2.0-flash')
OLLAMA_CHAT_MODEL = env('OLLAMA_CHAT_MODEL', default='llama3')

# OpenRouter Embedding Configuration
OPENROUTER_API_KEY = env('OPENROUTER_API_KEY', default='')
OPENROUTER_BASE_URL = env('OPENROUTER_BASE_URL', default='https://openrouter.ai/api/v1')
OPENROUTER_EMBEDDING_MODEL = env('OPENROUTER_EMBEDDING_MODEL', default='bge-m3')

# Chat API Configuration (OpenAI-compatible: OpenAI, DeepSeek, Together, etc.)
CHAT_API_KEY = env('CHAT_API_KEY', default='')
CHAT_BASE_URL = env('CHAT_BASE_URL', default='https://api.openai.com/v1')

# pgvector ivfflat index probe count
VECTOR_SEARCH_PROBES = env("VECTOR_SEARCH_PROBES")

# Chat Configuration (OpenAI-compatible: OpenAI, DeepSeek, Together, etc.)
OPENAI_CHAT_MODEL = env("OPENAI_CHAT_MODEL", default="gpt-4o-mini")
CHAT_MAX_TOKENS = env.int("CHAT_MAX_TOKENS", default=1000)

# Partial Answer Configuration (Global RAG per-hub partial answers)
# Lower than CHAT_MAX_TOKENS because each hub generates a focused partial
# answer using only its own context. Tuned for Persian legal text to avoid
# truncation while keeping per-hub responses concise.
PARTIAL_ANSWER_MAX_TOKENS = env.int("PARTIAL_ANSWER_MAX_TOKENS", default=800)

# Synthesis Configuration (Global RAG answer merging)
# Higher than CHAT_MAX_TOKENS because the synthesis step merges 3 partial
# answers (legislation, judicial precedent, advisory opinions) with conflict
# detection into a comprehensive Persian legal answer.
SYNTHESIS_MAX_TOKENS = env.int("SYNTHESIS_MAX_TOKENS", default=3000)

# RAG Configuration
RAG_MAX_HISTORY_TURNS = env.int("RAG_MAX_HISTORY_TURNS", default=10)
RAG_CONTEXT_TOKEN_BUDGET = env.int("RAG_CONTEXT_TOKEN_BUDGET", default=4000)

# Query Formulation (Epic E11)
QUERY_FORMULATION_ENABLED = env.bool("QUERY_FORMULATION_ENABLED", default=True)
QUERY_FORMULATION_MAX_TOKENS = env.int("QUERY_FORMULATION_MAX_TOKENS", default=1024)
QUERY_FORMULATION_TIMEOUT = env.int("QUERY_FORMULATION_TIMEOUT", default=15)  # seconds

# Persian Legal Text Processing
PERSIAN_NORMALIZATION_ENABLED = env.bool('PERSIAN_NORMALIZATION_ENABLED', default=True)
LEGAL_CHUNKING_ENABLED = env.bool('LEGAL_CHUNKING_ENABLED', default=True)
LEGAL_MAX_CHUNK_SIZE = env.int('LEGAL_MAX_CHUNK_SIZE', default=2000)
LEGAL_CHUNK_OVERLAP_CLAUSES = env.int('LEGAL_CHUNK_OVERLAP_CLAUSES', default=1)

# Non-Text Chunk Filtering (Epic E11)
NON_TEXT_CHUNK_FILTERING_ENABLED = env.bool('NON_TEXT_CHUNK_FILTERING_ENABLED', default=True)

# Extraction Strategy
# The page-level quality check uses a 5-signal score (stopwords, lexicon
# validity, bigram plausibility, RTL consistency, character entropy).
# Quality < threshold → routed to VLM extraction (Qwen3 VL via OpenRouter).
EXTRACTION_GARBLED_THRESHOLD = env.float('EXTRACTION_GARBLED_THRESHOLD', default=0.3)

# Vision Extraction (VLM) — replaces old EasyOCR/Tesseract/pdfplumber fallbacks
VISION_EXTRACTION_ENABLED = env.bool('VISION_EXTRACTION_ENABLED', default=True)
VISION_EXTRACTION_MODEL = env('VISION_EXTRACTION_MODEL', default='qwen/qwen3-vl-235b-a22b-instruct')
VISION_EXTRACTION_DPI = env.int('VISION_EXTRACTION_DPI', default=150)
VISION_EXTRACTION_MAX_RETRIES = env.int('VISION_EXTRACTION_MAX_RETRIES', default=3)

# Storage Configuration
STORAGE_TYPE = env('STORAGE_TYPE', default='local')
LOCAL_STORAGE_PATH = env('LOCAL_STORAGE_PATH', default=os.path.join(BASE_DIR, 'media/documents'))
S3_BUCKET_NAME = env('S3_BUCKET_NAME', default='docuchat-uploads')
S3_REGION = env('S3_REGION', default='us-east-1')

# File upload settings
MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50MB
ALLOWED_EXTENSIONS = ['.pdf', '.docx', '.txt']

# Logging
# Ensure logs directory exists
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Swagger/OpenAPI Documentation Settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Bearer {token}"'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch',
    ],
    'DOC_EXPANSION': 'list',
    'DEFAULT_MODEL_RENDERING': 'model',
    'VALIDATOR_URL': None,
}

# ---------------------------------------------------------------------------
# Anchor chunking settings
# ---------------------------------------------------------------------------
# Controls the new AnchorChunkingService which replaces the old
# ChunkingService and LegalStructureDetector.
ANCHOR_CHUNKING_ENABLED = True
ANCHOR_CHUNK_TOKENS = 400
ANCHOR_OVERLAP_TOKENS = 50

# ---------------------------------------------------------------------------
# Persian Legal Chunker settings (replaces AnchorChunkingService)
# ---------------------------------------------------------------------------
PERSIAN_LEGAL_CHUNKER_ENABLED = True
MIN_CHUNK_TOKENS = 150
MAX_CHUNK_TOKENS = 400  # Same as ANCHOR_CHUNK_TOKENS
OVERLAP_SENTENCES = 1

# ---------------------------------------------------------------------------
# Vision Extraction settings (Qwen3 VL via OpenRouter)
# ---------------------------------------------------------------------------
# Replaces the old EasyOCR + Tesseract + pdfplumber fallback chain.
# See VisionExtractionService for usage.
# VISION_EXTRACTION_ENABLED, VISION_EXTRACTION_MODEL, VISION_EXTRACTION_DPI,
# and VISION_EXTRACTION_MAX_RETRIES are defined in the Extraction Strategy section above.
