# Generated by Django 4.2.16 on 2026-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hub_metadata',
            field=models.JSONField(blank=True, default=None, help_text='Metadata for Global RAG queries: stores per-hub results, sub-queries, and hub-level token usage.', null=True),
        ),
    ]
