# Generated by Django 4.2.16 on 2026-05-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_hub_type_documentchunk_hub_type_and_more'),
        ('conversations', '0002_message_hub_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='documents.document'),
        ),
    ]
