# Generated by Django 4.2.16 on 2026-06-03 07:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_make_document_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_type', models.CharField(help_text='e.g., contract_dispute, family_law, criminal', max_length=100)),
                ('facts', models.JSONField(default=dict, help_text='Structured facts: {parties, claims, evidence, timeline, ...}')),
                ('completeness_score', models.FloatField(default=0.0, help_text='0.0 to 1.0 — how complete the fact profile is')),
                ('is_complete', models.BooleanField(default=False, help_text='True when enough facts have been gathered for analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_profiles',
            },
        ),
        migrations.CreateModel(
            name='StrategicReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success_probability', models.FloatField(help_text='0.0 to 1.0 — estimated likelihood of success')),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('applicable_laws', models.JSONField(default=list, help_text='[{title, articles, citations}]')),
                ('applicable_precedents', models.JSONField(default=list, help_text='[{title, number, summary}]')),
                ('raw_report', models.TextField(help_text='Full Persian markdown report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategic_reports',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('local_rag', 'Local RAG'), ('global_rag', 'Global RAG / Legal Research'), ('strategist', 'Interactive Strategist'), ('action_engine', 'Action Engine')], default='global_rag', help_text='Conversation mode: local_rag, global_rag, strategist, or action_engine. Null defaults to global_rag for backward compatibility.', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['mode'], name='conversatio_mode_a07256_idx'),
        ),
        migrations.AddField(
            model_name='strategicreport',
            name='case_profile',
            field=models.ForeignKey(help_text='The case profile this report was generated from', on_delete=django.db.models.deletion.CASCADE, to='conversations.caseprofile'),
        ),
        migrations.AddField(
            model_name='strategicreport',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_report', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_profile', to='conversations.conversation'),
        ),
        migrations.AddIndex(
            model_name='strategicreport',
            index=models.Index(fields=['conversation'], name='strategic_r_convers_838118_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicreport',
            index=models.Index(fields=['case_profile'], name='strategic_r_case_pr_1f1321_idx'),
        ),
        migrations.AddIndex(
            model_name='caseprofile',
            index=models.Index(fields=['conversation'], name='case_profil_convers_22cab6_idx'),
        ),
        migrations.AddIndex(
            model_name='caseprofile',
            index=models.Index(fields=['case_type'], name='case_profil_case_ty_d7a4f3_idx'),
        ),
    ]
