# Generated by Django 4.2.21 on 2026-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_add_mode_caseprofile_strategicreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicreport',
            name='civil_pathway',
            field=models.TextField(blank=True, default='', help_text='Complete civil/legal pathway analysis'),
        ),
        migrations.AddField(
            model_name='strategicreport',
            name='criminal_pathway',
            field=models.TextField(blank=True, default='', help_text='Complete criminal pathway analysis'),
        ),
        migrations.AddField(
            model_name='strategicreport',
            name='missing_facts',
            field=models.JSONField(blank=True, default=list, help_text='List of information gaps identified in the case'),
        ),
        migrations.AddField(
            model_name='strategicreport',
            name='pathways_relation',
            field=models.TextField(blank=True, default='', help_text='How civil and criminal pathways interact'),
        ),
        migrations.AddField(
            model_name='strategicreport',
            name='risk_assessment',
            field=models.JSONField(blank=True, default=dict, help_text='{strengths, weaknesses, success_probability}'),
        ),
        migrations.AddField(
            model_name='strategicreport',
            name='sources_used',
            field=models.JSONField(blank=True, default=list, help_text='List of source citations used in the analysis'),
        ),
        migrations.AddField(
            model_name='strategicreport',
            name='strategic_recommendation',
            field=models.TextField(blank=True, default='', help_text='Recommended next action'),
        ),
    ]
